@startuml espaditas

class Juego{

}
class Menu {
    -start : option
    -controls : option
    -exit : option
    +RenderMenu() : void
}

class option {
    
}
class LifeBar{
    -height : int
    -width : int
    
}
class Player{
    -life : int
    -height : int
    -width : int
    +TakeDamage() : int
    +HoldSwort() : bool
    +MoveSwort() :
    +ThrowSword() : 
    +Dash() :
}
class Sword{
    -damage : int
    -height : int
    -width : int
}
class Arena{

}
class Bamboo{

}
class Colisionable{

}
class Atravesable{

}
class Piso{

}
class Nube{

}



Juego "1" *--  "2" Arena


Arena "1" *-- "*" Bamboo
Arena "1" *-- "*" Nube
Arena "1" *-- "4" Sword
Arena "1" *-- "1" Piso
Arena "1" *-- "2" Player
Piso "1" *-- "1" Bamboo


Player o-- Bamboo
Player "1" o-- "1" Sword
Player "1" *-- "1" LifeBar


Bamboo <|-- Atravesable
Nube <|-- Atravesable
Sword <|-- Atravesable

Player <|-- Colisionable
Bamboo <|-- Colisionable
Piso <|-- Colisionable


@enduml
