@startuml espaditas

class Game{
    - menu: Menu
    - window: sf::RenderWindow

    + Game()
    + ~Game()
    + run(): void
}
class Menu {
    + startFunction(window: sf::RenderWindow*): void
    + exitFunction(): void
    + controlsFunction(): void
    + printMenu(menuWindow: sf::RenderWindow*): void
}
class Player{
    - body: b2Body*
    - sprite1: sf::Sprite
    - sprite2: sf::Sprite
    - runIdle: Animation
    - jumpDash: Animation
    - dashTimer: sf::Clock
    - dashDurationTimer: sf::Clock
    - clock: sf::Clock
    - dashCounter: int
    - lives: int
    - dashAvailable: bool
    - isDashing: bool

    + Player()
    + Player(world: b2World, x: float, y: float, width: float, height: float, texture1: sf::Texture*, texture2: sf::Texture*)
    + draw(spt: int, window: sf::RenderWindow&): void
    + update(spt: int, row: int, deltaTime: float, direction: bool): void
    + startDash(): void 
    + startCoolDown(): void
    + dashState(): void
    + coolDown(): void
    + getBody(): b2Body*
    + dash(dashForce: float): void
    + reset(world: b2World, x: float, y: float, width: float, height: float, texture1: sf::Texture*, texture2: sf::Texture*): void
    + getDashCounter() const: int
    + increaseDashCounter(): void
    + isDashAvailable(): bool
    + isPlayerDashing(): bool
    + areYouLive(): bool
}
class Arena{
    - window: sf::RenderWindow*
    - world: b2World
    - ground: Collidable
    - LimIz: Collidable
    - LimDer: Collidable
    - LimSup: Collidable
    - player1: Player
    - player2: Player
    - player1TextureRunIdle: sf::Texture
    - player2TextureRunIdle: sf::Texture
    - player1TextureJumpDash: sf::Texture
    - player2TextureJumpDash: sf::Texture
    - fondoTexture: sf::Texture
    - fondoSprite: sf::Sprite
    - contactListener: ContactListener
    - desiredSpeed: float
    - gameInProgres: int
    - row1: int
    - spt1: int
    - spt2: int
    - row2: int
    - right1: bool
    - right2: bool

    + Arena(window: sf::RenderWindow*)
    + run(): int
    - processEvents(): void
    - update(): void
    - render(): void
}
class Collidable{
    - body: b2Body*
    - shape: sf::RectangleShape

    + Collidable(world: b2World, x: float, y: float, width: float, height: float)
    + draw(window: sf::RenderWindow): void
    + getBody(): b2Body*
}
class Sound{
    - buffer: sf::SoundBuffer
    - sound: sf::Sound
    - music: sf::Music

    + Sound()
    + ~Sound()
    + PlaySound(soundpath: std::string): void
    + PlayMusic(musicpath: std::string): void
    + StopMusic(): void
    + StopSound(): void
    + musicVolume(volume: float): void
}
class Animation{
    - uvRect: sf::IntRect
    - imageCount: sf::Vector2u
    - currentImage: sf::Vector2u
    - totalTime: float
    - switchTime: float

    + Animation()
    + Animation(texture: sf::Texture*, imageCount: sf::Vector2u, switchTime: float)
    + ~Animation()
    + Update(row: int, deltaTime: float, faceRight: bool): void
}
class Button{
    - button: sf::RectangleShape
    - texture: sf::Texture*
    - position: sf::Vector2f
    - size: sf::Vector2f

    + Button(size: sf::Vector2f, position: sf::Vector2f, texture: sf::Texture*)
    + ~Button()
    + Draw(window: sf::RenderWindow): void
    + Update(deltaTime: float): void
    + IsPressed(window: sf::RenderWindow): bool
}
class ContactListener{
    - player1OnGround: bool
    - player2OnGround: bool
    - playersInContact: bool

    + ContactListener()
    + BeginContact(contact: b2Contact): void
    + EndContact(contact: b2Contact): void
    + isPlayer1OnGround() const: bool
    + isPlayer2OnGround() const: bool
    + arePlayersInContact() const: bool
}

class sf::RenderWindow {}
class sf::IntRect {}
class sf::Vector2u {}
class sf::Clock {}
class sf::Sprite {}
class sf::Texture {}
class sf::Vector2f {}
class sf::RectangleShape {}
class sf::SoundBuffer {}
class sf::Sound {}
class sf::Music {}
class b2World {}
class b2Body {}
class b2Contact {}
class b2ContactListener {}

Arena "1" o-- "1" sf::RenderWindow
Arena "1" *-- "1" b2World
Arena "1" *-- "4" Collidable
Arena "1" *-- "2" Player
Arena "1" *-- "5" sf::Texture
Arena "1" *-- "1" sf::Sprite
Arena "1" *-- "1" ContactListener

Player "1" *-- "1" sf::Sprite
Player "1" *-- "2" Animation
Player "1" *-- "3" sf::Clock
Player "1" *-- "1" b2Body
Player "1" o-- "1" b2World
Player "1" o-- "2" sf::Texture
Player "1" o-- "1" sf::RenderWindow

Collidable "1" *-- "1" sf::RectangleShape
Collidable "1" *-- "1" b2Body
Collidable "1" o-- "1" b2World
Collidable "1" o-- "1" sf::RenderWindow

Menu "1" o-- "1" sf::RenderWindow
Menu "1" *-- "1" Arena
Menu "1" *-- "5" Button
Menu "1" *-- "3" Sound
Menu "1" *-- "1" sf::Event
Menu "1" *-- "7" sf::Texture
Menu "1" *-- "2" sf::Vector2f
Menu "1" *-- "2" sf::RectangleShape

Game "1" *-- "1" Menu
Game "1" *-- "1" sf::RenderWindow

Animation "1" o-- "1" sf::Texture
Animation "1" *-- "1" sf::IntRect
Animation "1" *-- "2" sf::Vector2u

Sound "1" *-- "1" sf::SoundBuffer
Sound "1" *-- "1" sf::Sound
Sound "1" *-- "1" sf::Music

ContactListener "1" o-- "1" b2Contact
ContactListener <|-- b2ContactListener

@enduml